// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD22xagUs2wtcL-bDos-sUkRSG2fTxeXb8',
    appId: '1:762314732370:web:114bf666dcdb67988dc08b',
    messagingSenderId: '762314732370',
    projectId: 'todo-app-5bf28',
    authDomain: 'todo-app-5bf28.firebaseapp.com',
    storageBucket: 'todo-app-5bf28.appspot.com',
    measurementId: 'G-WVBP6HEB5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGF-ECxb1LOjhEWxHVLT9KSjb7lBqznTg',
    appId: '1:762314732370:android:f0afb436774171948dc08b',
    messagingSenderId: '762314732370',
    projectId: 'todo-app-5bf28',
    storageBucket: 'todo-app-5bf28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCspRM14_SOK-h2lPphromf90O0btXr1Zc',
    appId: '1:762314732370:ios:0667a2488cd0c5ee8dc08b',
    messagingSenderId: '762314732370',
    projectId: 'todo-app-5bf28',
    storageBucket: 'todo-app-5bf28.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCspRM14_SOK-h2lPphromf90O0btXr1Zc',
    appId: '1:762314732370:ios:0667a2488cd0c5ee8dc08b',
    messagingSenderId: '762314732370',
    projectId: 'todo-app-5bf28',
    storageBucket: 'todo-app-5bf28.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD22xagUs2wtcL-bDos-sUkRSG2fTxeXb8',
    appId: '1:762314732370:web:5291f826fe4cde948dc08b',
    messagingSenderId: '762314732370',
    projectId: 'todo-app-5bf28',
    authDomain: 'todo-app-5bf28.firebaseapp.com',
    storageBucket: 'todo-app-5bf28.appspot.com',
    measurementId: 'G-13KB4V3D8R',
  );

}